### ISSUE TITLE
Invalid input file causes a 500 Internal Server Error

### ISSUE THREAD

**Issue by xird** [skyderby/skyderby#434]
On 2023-07-28 in the Finnish Nationals, a competitor's FlySight generated a CSV file that had a single line out of order based on the timestamp. When the judges tried to upload the file, Skyderby returned an error saying "Something went wrong". With developer tools, I saw that it was a 500 Internal Server Error.

Since the cause of the error is an invalid input file, the proper error to return would be a 400 Invalid Request, with a human-readable error saying something like "The file you tried to upload is not valid".

Attached is the file in question, with the offending line on line 43.

[18-31-22-k5-Saikko.CSV](https://github.com/skyderby/skyderby/files/12190708/18-31-22-k5-Saikko.CSV)

**Comment by xird** [comment]
I tried to start debugging this, but after setting up my local environment and trying to upload a _valid_ track file, I got these errors in the log:

```
Started POST "/api/v1/tracks" for 127.0.0.1 at 2023-07-28 09:42:11 +0300
Processing by Api::V1::TracksController#create as JSON
  Parameters: {"track"=>{"comment"=>"", "location"=>"EFLA", "kind"=>"skydive", "visibility"=>"public_track", "trackFileId"=>3, "segment"=>0, "suitId"=>1}}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Profile Load (0.4ms)  SELECT "profiles".* FROM "profiles" WHERE "profiles"."owner_id" = $1 AND "profiles"."owner_type" = $2 LIMIT $3  [["owner_id", 2], ["owner_type", "User"], ["LIMIT", 1]]
  Announcement Load (0.5ms)  SELECT "announcements".* FROM "announcements" WHERE (NOW() BETWEEN period_from AND period_to)
Unpermitted parameter: :segment. Context: { controller: Api::V1::TracksController, action: create, request: #<ActionDispatch::Request:0x00007fb4edd5f7b0>, params: {"track"=>{"comment"=>"", "location"=>"EFLA", "kind"=>"skydive", "visibility"=>"public_track", "trackFileId"=>3, "segment"=>0, "suitId"=>1}, "format"=>:json, "controller"=>"api/v1/tracks", "action"=>"create"} }
  TRANSACTION (0.2ms)  BEGIN
  Track::File Load (0.3ms)  SELECT "track_files".* FROM "track_files" WHERE "track_files"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  TRANSACTION (0.6ms)  ROLLBACK
Completed 500 Internal Server Error in 1465ms (ActiveRecord: 2.4ms | Allocations: 780998)


  
JSON::ParserError (784: unexpected token at '<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>'):
  
app/services/track_scanner.rb:85:in `check_status'
app/services/track_scanner.rb:65:in `call'
app/services/track_scanner.rb:55:in `call'
app/services/create_track_service.rb:89:in `jump_range'
app/services/create_track_service.rb:54:in `set_jump_range'
app/services/create_track_service.rb:24:in `block in call'
app/services/create_track_service.rb:21:in `call'
app/services/create_track_service.rb:12:in `call'
app/controllers/api/v1/tracks_controller.rb:20:in `create'
```

**Comment by skyksandr** [comment]
Ah, right. Heroku stopped providing hosting service for free. 
So in order to run it locally you need to use docker, start `skyderby/track-scanner` container in it mapping ports like `8000:80` and point app to it via environment variable
```
TRACK_SCANNER_URL=http://localhost:8000
```

**Comment by skyksandr** [comment]
Regarding original issue - one option is to cut this part of a file. 
How I was going to solve it - I planned to rewrite this part of app from magic machine learning cascade of decision trees and SVM to just ruby code and make it indifferent to missing samples

**Comment by xird** [comment]
I managed to get track scanner running, but it doesn't look like that's the issue. From the original log above:

```
Unpermitted parameter: :segment. Context: { controller: Api::V1::TracksController, action: create, request: #<ActionDispatch::Request:0x00007f06db4ecf80>, params: {"track"=>{"comment"=>"", "location"=>"efla", "kind"=>"skydive", "visibility"=>"public_track", "trackFileId"=>5, "segment"=>0, "suitId"=>1}, "format"=>:json, "controller"=>"api/v1/tracks", "action"=>"create"} }
```

What's "segment"?

**Comment by xird** [comment]
I created a PR improving the README re: running track-scanner: https://github.com/skyderby/skyderby/pull/435

**Comment by skyksandr** [comment]
Exit and opening detection were (finally) fully rewritten. No more HTTPS 500s. At least at this part of the app
